name = "bootloader-thumbnail-renderer"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = ""

[browser]
binding = "MYBROWSER"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "media.bootloader.art"
custom_domain = true